# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a7a84540d7151395096af6a88da1e3ca112054c7e37cbb6ec70a468e3a33543be78a17514a676b425d89639c648e04d4dd2eb64f436e42a3fe3f26a33a9c1ec

test:
  secret_key_base: 32000df58527c74edf3963b99de75960699882397291e886ae208c1b0d58c838d32ea6627e90a0c4cb17f825e9e4f91b2b7c72f7fc4fcbe6657f409d7fc0cb5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
